### ISSUE TITLE
Enhancement request: Add a macro to apply grouped transparency to a tex hbox/vbox

### ISSUE THREAD

**Issue by poetaman** [ho-tex/transparent#5]
Hi Heiko,

The current text transparency model used by latex (using fontspec  option opacity or package transparent) is insufficient for a lot of scripts, and fonts. It seems like the problem can be solved by either putting a hbox/vbox (that contains text) into a pdf transparency group, or if that's not possible then by putting contents of package textpos's environment textblock (which has a known absolute location in pdf) into transparency group. I read pdftex manual's interface `\pdfxform`, though I did not understand it enough to be able to use it. This package might be a natural place to add a macro that takes a tex box, and wraps it in a transparency group with user-specified blend mode. Here's the question posted on TeX.SE: https://tex.stackexchange.com/q/565281/192717

Thanks!

**Comment by u-fischer** [comment]
Your examples on tex.sx (both the tikz and the indesign example) use Form XObjects, so basically boxes.  The transparent package is about text which can contains page breaks: it restores transparency with the help of a color stack on the second page. It doesn't use boxes, so it isn't a natural place for a box command--- `transparent` would only come into play if you find an example that sets the transparency group for running text.   tikz, l3draft or something based on xsavebox is currently imho more fitting.

**Comment by poetaman** [comment]
@u-fischer Thanks for the inputs. Do you think [package luacolor](https://ctan.org/pkg/luacolor?lang=en) with its `\luacolorProcessBox` would be a better place. Its manual says "Before passing a box to \pdfxform, call \luacolorProcessBox first.", so it already seems to have code to handle XObjects.

**Comment by u-fischer** [comment]
No, luacolor is not really relevant either. It could perhaps be extended to add blend mode to form xobjects, but where is the point if you can add it at creation of the objects? Why don't you use the tikz solution you got?

**Comment by poetaman** [comment]
@u-fischer Because as someone trying to author a document that mixes English (set in Latin) & Sanskrit (set in Devanagari), I would have many such boxes. Given tikz pictures tend to be slow<sup>\[1\]</sup> (among other idiosyncrasies tikz might pose) and given there is no real tikz graphic drawing here, it will be beneficial to have the tikz pgf's  transparency group code work outside of tikzpicture. This will benefit multiple non-Latin script based communities using latex.

<sup>\[1\]</sup> One could argue that all tikz pictures can be externalized to improve performance. But for a non-Latin script user this could mean each page of their document will have to get externalized (too much unnecessary memory, and potential file read/write time), or if they do not choose externalization then adding a new "tikz" textbox would recompile all tikz pictures down the line (afaik). Both options do not seem lucrative.

**Comment by dcpurton** [comment]
@reportaman You could optimise the implementation by using just the raw pgf commands and leaving the `tikz` overhead out. I doubt that this would be that much slower than my other answer and doesn't have as many limitations.

Something like this:

```TeX
%! TeX Program = lualatex

\documentclass{article}

\usepackage{l3pdf}
\usepackage{xparse}
\usepackage{pgf}

\ExplSyntaxOn

\pdf_uncompress:

\NewDocumentEnvironment { transparencygroup }
  { m +b }
  {
    \vbox_set:Nn \l_tmpa_box { #2 }
    \noindent
    \begin { pgfpicture }
      \pgfsetfillopacity { #1 }
      \begin { pgftransparencygroup } [ isolated=true ]
        \pgftext { \box_use_drop:N \l_tmpa_box }
      \end { pgftransparencygroup }
    \end { pgfpicture }
  }
  { }

\ExplSyntaxOff

\usepackage{lipsum}
\usepackage{fontspec}

\newfontfamily{\devanagarifamtext}{Noto Sans Devanagari}[Script=Devanagari, Scale=1, Renderer=HarfBuzz, Color=FF0000, Opacity=0.25]
\newfontfamily{\devanagarifampgf}{Noto Sans Devanagari}[Script=Devanagari, Scale=1, Renderer=HarfBuzz, Color=FF0000]

\begin{document}
\begin{transparencygroup}{0.5}
  {\Huge\devanagarifampgf एक गांव में पिताजी}

  \lipsum[1]
\end{transparencygroup}

{\Huge\devanagarifamtext एक गांव में पिताजी}
\end{document}
```

**Comment by u-fischer** [comment]
> Because as someone trying to author a document that mixes English (set in Latin) & Sanskrit (set in Devanagari), I would have many such boxes.

Well opacity is sometimes quite nice, but I haven't seen a text using it a lot and I don't quite see why a text in devanagari should be different here. 

> Given tikz pictures tend to be slow

Large tikz pictures with lots of calculations and pathes and curves can be slow. But you are setting here only a node, and if time matters much you can avoid some of the tikz overhead with David's code. A solution outside tikz would be not very difficult to implement if you are a bit careful with ExtGState but it would be not much different to the tikz code, and you would loose all the tikz goodies, regarding colors, shifts, frames, decorations etc.
